name: Run

on:
  push:
    branches: [ "*" ]

  pull_request:
    branches: [ "*" ]

jobs:
  build:
    uses: ktomk/run-travis-yml@v1
    with:
        file: .travis.yml
        steps: |
          install
          script
        allow-failure: false



